### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore` resource when creating or updating using account console

### ISSUE THREAD

**Issue by cmollgaard** [databricks/terraform-provider-databricks#1675]
### Configuration
```hcl

provider "databricks" {
  host       = "https://accounts.azuredatabricks.net"
  account_id = "account_id" # Replace with working ID
  auth_type  = "azure-cli"
}

resource "databricks_metastore" "this" {
  name = "metastore"
  storage_root = format("abfss://%s@%s.dfs.core.windows.net/",
    "container",
    "storageaccount")
}
```

### Expected Behavior

I would expect a metastore to be created
### Actual Behavior

Metastore fails with HTTP error
Error: cannot create metastore: invalid character '<' looking for beginning of value
│ <!doctype html><html lang="en"><... (695 more bytes)
│
│   with databricks_metastore.this,
│   on main.tf line 113, in resource "databricks_metastore" "this":
│  113: resource "databricks_metastore" "this" {

### Steps to Reproduce
1. `terraform apply`
2. Accept changes with yes

### Terraform and provider versions

databricks provider 1.6 
terraform 1.3.2

### Debug Output

https://gist.github.com/cmollgaard/a6a478b39b035a4d5e65ad1f36db44cc

**Comment by nkvuong** [comment]
@cmollgaard what identity are you using to authenticate the `az cli`?

**Comment by nfx** [comment]
Please run it with debug_truncate_bytes = 2048, that html error response may have something useful to explain this error

**Comment by nfx** [comment]
Platform APIs are not yet available

**Comment by fludo** [comment]
@nfx  Any idea when the API will be available, and when the provider will support It ? We don't want to lose a metastore by mistake because we destroy the workspace : this is a serious blocker since private endpoint require us to recreate the workspace.

Metastore sharing accross workspace is also recommanded by Databricks it.

**Comment by nfx** [comment]
@fludo we cannot share those timelines as of now.

**Comment by BostjanBozic** [comment]
It would be great to have this API available, since this removes the possibility to deploy metastore independent from workspace.
As a use-case, lets say you have TF codebase with base infrastructure in place and separate TF module, which is building up workspaces (same module reused across multiple workspaces). Currently one workspace needs to be created in base infrastructure codebase to generate token, so that metastore can get deployed (authentication toward workspace).

With account-level API that would not be a problem anymore and it would feel more natural, since metastore is shared across multiple workspaces (on AWS one metastore per region).

**Comment by joshwright10** [comment]
I'm here after also hitting this unexpected limitation. With Unity Catalog being a shared service, I was hoping to manage it independently of a workspace, as we have many different workspaces.
@nfx is it not possible to leave this open as a feature request?

**Comment by SapphicCode** [comment]
Agreed. Please re-open or at least leave a note in the documentation.
