### ISSUE TITLE
[ISSUE] Issue with `databricks_permissions` resource. Permissions are missing on notebooks & directories

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1850]
When `access` is added to the list of services, the user of the exporter reports that permission on notebook and directories are not created as a `resource databricks_permission` terraform resource block.

### Expected Behavior
Permissions granted to users other than the owner / author of the notebook should be reflected in the exported output

### Actual Behavior
Permission resource blocks are missing (at least for notebook and directories) and for other objects, also.

**Comment by qili86** [comment]
Hi @nfx and @rohitnijhawan , I am working on this fix, and I have the fix in my local branch issues_1850, and tested
now I am trying to push this branch to make a PR, and it shows the authentication error below. Just wondering how you guys pushed your fixed branch. Thank you!

qi.li@X9NWF957DL terraform-provider-databricks % git push --set-upstream origin issues_1850
Username for 'https://github.com': qili86
Password for 'https://qili86@github.com':
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/databricks/terraform-provider-databricks.git/'

**Comment by qili86** [comment]
I figured out instead of using password authentication, I changed to use SSH auth, and it seems I don't have the right permission

qi.li@X9NWF957DL terraform-provider-databricks % git push --set-upstream origin issues_1850
ERROR: Permission to databricks/terraform-provider-databricks.git denied to qili86.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by nfx** [comment]
Please create a PR from the fork
