### ISSUE TITLE
[FEATURE] Allow databricks_metastore to be be managed independently of Azure Workspaces

### ISSUE THREAD

**Issue by joshwright10** [databricks/terraform-provider-databricks#1877]
### Use-cases

As a Metastore is a shared resource for all Workspaces in that region, it would make sense to manage this independently of Azure Databricks Workspaces, especially for large organizations with many Databricks Workspaces.

This would allow for a Terraform project to manage Metastores, related storage accounts, etc. all in one central config, not tying it to a Workspace, or creating a dummy workspace as a workaround. 

### Attempted Solutions

A workaround is to create a dummy Workspace.

### Proposal

Allow `databricks_metastore` resources to be created and managed directly through the Account Console `https://accounts.azuredatabricks.net` using a Service Principal without the need for an existing Azure Databricks Workspace.

### References

This has already been discussed  in #1675.

**Comment by ePak** [comment]
The same applies to Databricks on AWS.

**Comment by Aerodynamite** [comment]
This absolutely needs to be implemented. Setting up a reusable terraform configuration for a unity catalog with multiple metastores and multiple workspaces is an absolute nightmare on Azure. 

- You can't create a unity catalog without a workspace.
- You can't create a unity catalog metastore catalog without a workspace that has been assigned to the metastore.
- The databricks provider can only be linked to one workspace, so you need an provider alias for each workspace you wish to assign to the unity catalog.
- Due to the above limitation, you need to create about 5 different terraform modules with explicit depends_on configurations to satisfy the ungodly amount of strange order-of-operation expectations with the unity catalog metastore setup.

**Comment by nkvuong** [comment]
Close by #2182
