### ISSUE TITLE
[FEATURE] Support creating notification destinations

### ISSUE THREAD

**Issue by Esya** [databricks/terraform-provider-databricks#1983]
### Use-cases
Right now it is possible when creating a `Job`  to set `webhook_notifications` to an array of notification destination IDs, such as :

```
"on_failure": [ { "id": "0481e838-0a59-4eff-9541-a4ca6f149574" } ]
```

But there is no way to create those notification destinations through the provider. We create whole workspaces using Terraform and configure them entirely - and we would like to have Slack alerts for jobs set-up automatically on every job. 

### Attempted Solutions
Right now the only solution is to manually create the destinations in the workspaces, save the IDs, and use those IDs in Terraform.
The problem with this is that we cannot create an entirely new workspace in one run.

### Proposal
Have an `alert_destination` resource that matches what's visible in the UI, for example for Slack, `Name` and `Webhook URL`
![image](https://user-images.githubusercontent.com/937179/217040774-64c9de92-a3e6-486a-9d67-9126dd842d8d.png)

It seems that the API used by the Workspace UI to create alert destinations is not documented though, and it does not appear in the [REST API (Latest) documentation](https://docs.databricks.com/dev-tools/api/latest/index.html) unless I'm missing something ?

**Comment by alexott** [comment]
it's not implemented because there is no public API for that functionality. As soon as it will be added, new resource will be created

**Comment by fdvieira** [comment]
Hello,

Any news on this? We would like to use this in terraform resource!
Francisco

**Comment by alexott** [comment]
No public API still, and no ETA yet

**Comment by rondefreitas** [comment]
It looks like the feature itself is now GA. Any word on the API required to leverage it through GO and terraform?

**Comment by alexott** [comment]
Nope

**Comment by nchammas** [comment]
If you have some existing notification destinations, which I am currently looking at via this URL,

```
https://<workspace-name>.cloud.databricks.com/settings/workspace/notifications/notification-destinations
```

is there some way to get the `id` of one of those existing destinations?

The [documentation for `webhook_notifications` says][1]:

> The `id` can be retrieved through the API or the URL of Databricks UI `https://<workspace host>/sql/destinations/<notification id>?o=<workspace id>`

But this doesn't make sense since this URL contains the notification ID we're trying to find in the first place! And I can't see a way via the Databricks CLI or REST API to find the ID of an existing notification destination.

Is it even possible?

I agree with the original issue that it would best if we could manage notification destinations using Terraform. However, I'm struggling to even use existing notification destinations via Terraform.

[1]: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#webhook_notifications-configuration-block

**Comment by nchammas** [comment]
OK, a colleague pointed out that this information is available in the web UI behind this nondescript "copy" icon:

<img width=600 src="https://github.com/databricks/terraform-provider-databricks/assets/1039369/59b9087f-c386-4a63-9ea2-ad19916d09eb" />

Still can't find a way to get this same information via the CLI or REST API ([as excepted][1]), but at least we can do it manually.

[1]: https://github.com/databricks/terraform-provider-databricks/issues/1983#issuecomment-1419905088

**Comment by alexott** [comment]
API is now available: https://docs.databricks.com/api/workspace/notificationdestinations, but we need to get new Go SDK released to work on it.

**Comment by alexott** [comment]
Closing this as #3820 is merged now
