### ISSUE TITLE
[DOC] Why was docs/resources/table.md removed in e9bcc2d51a0cd065cafed57747ba61b1e95f5674

### ISSUE THREAD

**Issue by aucampia** [databricks/terraform-provider-databricks#2009]
### Affected Resource(s)

The affected resource is <https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/table>.

### Expected Details

As far as I can tell the provider still provides `resource "databricks_table"` [[ref](https://github.com/databricks/terraform-provider-databricks/blob/83c9e045b689aca2d87dd8ace59ee7eb24e2e7f5/catalog/resource_table.go)], however it seems the documentation for this was removed in e9bcc2d51a0cd065cafed57747ba61b1e95f5674. It was available still in release 1.6.5 [[ref](https://registry.terraform.io/providers/databricks/databricks/1.9.2/docs/resources/table)]

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- Add back documentation for `resource "databricks_table"`

### References

- Problem introduced in https://github.com/databricks/terraform-provider-databricks/pull/1836

**Comment by nkvuong** [comment]
@aucampia the UC Table APIs only supports Read & Delete, per the latest API spec - https://docs.databricks.com/api-explorer/workspace/tables. 

For Create & Update, there are many cases where it does not work, hence they remain undocumented and unsupported. Because of this, the `databricks_table` resource is hidden from the doc, even though the code remains available for customers who have previously created tables via Terraform.
