### ISSUE TITLE
[DOC] Wrong information in docs

### ISSUE THREAD

**Issue by kadu-vido** [databricks/terraform-provider-databricks#2010]
### Affected Resource(s)
[Doc page](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces#example-usage) for `databricks_mws_workspaces`, first block of code after "Example Usage" header

### Expected Details
The example in this block contains the following code:
```
variable "databricks_account_id" {
  description = "Account Id that could be found in the bottom left corner of https://accounts.cloud.databricks.com/"
}
```
At least in my org's account, this information can not be found at the specified location. After fiddling with the interface for a while unfruitfully, I gave up found the account ID in a different (private) repo owned by my company and moved on.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Provide a source for this information that works for all customers

### Important Factoids
This is what I see at the suggested page:
<img width="732" alt="db-account" src="https://user-images.githubusercontent.com/5318737/219324775-74975ea4-fbe3-4a02-9cef-da6bcf7c0327.png">
(redacted: my workspace name and work email)

### References
n/a

**Comment by iandexter** [comment]
Hi, @kadu-vido -- you're correct, the accounts admin console has changed since this doc was written. The account ID can be found in the dropdown under your email address in the upper-right corner: 

![image](https://user-images.githubusercontent.com/79125/219326892-ad1dd80c-b64a-46ea-a754-93befa5c0e7c.png)

We will change this accordingly. Thanks for reporting.
