### ISSUE TITLE
[ISSUE] Issue with `databricks_share` update detection

### ISSUE THREAD

**Issue by marekbrysa** [databricks/terraform-provider-databricks#2167]
### Configuration
Adding a new `object` to a `databricks_share` resource e.g.
```hcl
databricks_share my_share {
  name = "my_share"
  object {
    data_object_type = "TABLE"
    name = "main.foo.table_A"
  }
  object {
    data_object_type = "TABLE"
    name = "main.foo.table_C"
  }
}
```
->
```hcl
databricks_share my_share {
  name = "my_share"
  object {
    data_object_type = "TABLE"
    name = "main.foo.table_A"
  }
  object {
    data_object_type = "TABLE"
    name = "main.foo.table_B"
  }
  object {
    data_object_type = "TABLE"
    name = "main.foo.table_C"
  }
}
```

### Expected Behavior
Object for `main.foo.table_B` is added to the share

### Actual Behavior
Apply fails with `cannot update share: Shared Table 'foo.table_C' already exists`

When explicitly providing `shared_as` both before and after adding new object, it works.

Most likely https://github.com/databricks/terraform-provider-databricks/blob/0693e4c31f4fa84f2e01d5b0f75271f4c0b46fd8/catalog/resource_share.go#L152 does not work as expected.

### Terraform and provider versions
1.10.0

**Comment by marekbrysa** [comment]
The workaround is to explicitly specify `shared_as = "foo.table_X"` for all objects in the share, i.e. explicitly set the default value for `shared_as`.

**Comment by junwei-db** [comment]
Re-opening because we observe the issue still persists after the fix in https://github.com/databricks/terraform-provider-databricks/pull/2197. 

Here's another example of the current behavior:

Deleting table A from `databricks_share` resource,

from:
```
databricks_share my_share {
  name = "my_share"
  object {
    name = "main.foo.table_A"
    shared_as = "foo.table_A"
  }
  object {
    name = "main.foo.table_B"
    shared_as = "foo.table_B"
  }
}
```

to:
```
databricks_share my_share {
  name = "my_share"
  object {
    name = "main.foo.table_B"
    shared_as = "foo.table_B"
  }
}
```

Expected terraform plan:

`table_A` is deleted.

Actual terraform plan:

Change table A to table B and delete table B.

This plan will result in failure because changing `shared_as` is not supported.

The root cause is that terraform is not able to identify the same object, which leads to object mismatch and incorrect plan.

**Comment by junwei-db** [comment]
@nkvuong Could you take another look of this issue and see if it's possible to fix? We (system table team) are using delta sharing through terraform extensively, and this issue makes it hard to deploy any share changes. Thanks.

**Comment by junwei-db** [comment]
@nfx When is the expected release date for #2307?
