### ISSUE TITLE
[ISSUE] Issue with `databricks_user` resource

### ISSUE THREAD

**Issue by ralphkootker** [databricks/terraform-provider-databricks#2209]
The databricks_user resources is not updating the "external_id" attribute. As a result, each new terraform apply run, will try to modify the external_id and set the value again:

Running a terraform script to pull an AD group and its members from Active Directory and sync it to Databricks. This is on top of the SCIM/User provisioning we have setup for functional groups.

```terraform
locals {
  groups = [
    "databricks-test-group"
    # add more groups here
  ]
}


########################################################################
###
###   Test: Sync Azure AD groups with Databricks including it's users
###   
########################################################################

// read group members of given groups from AzureAD every time Terraform is started
data "azuread_group" "this" {
  for_each     = toset(local.groups)
  display_name = each.value
}

output "azuread_group_output" {
  value = {
    for k, bd in data.azuread_group.this : k => bd.id
  }
}

// create or remove groups within databricks - all governed by "groups" variable
resource "databricks_group" "this" {
  provider     = databricks.mws
  for_each     = data.azuread_group.this
  display_name = each.key
  external_id  = each.value.id
  #workspace_access      = var.groups[each.key].workspace_access
  #databricks_sql_access = var.groups[each.key].databricks_sql_access
}

output "databricks_group_output" {
  value = {
    for k, bd in databricks_group.this : k => bd.id
  }
}


// read users from AzureAD every time Terraform is started
data "azuread_user" "this" {
  for_each  = toset(flatten([for g in data.azuread_group.this : g.members]))
  object_id = each.value
}

output "azuread_user_output" {
  value = {
    for k, bd in data.azuread_user.this : k => bd.user_principal_name
  }
}


resource "databricks_user" "this" {
  provider     = databricks.mws
  for_each     = data.azuread_user.this
  **external_id  = each.value.id**
  user_name    = each.value.user_principal_name
  display_name = each.value.display_name
  active       = each.value.account_enabled
  force        = true
}
```

Issue sits in:
```
resource "databricks_user" "this" {
  provider     = databricks.mws
  for_each     = data.azuread_user.this
  **external_id  = each.value.id**
  user_name    = each.value.user_principal_name
  display_name = each.value.display_name
  active       = each.value.account_enabled
  force        = true
}
```

on line 4: `external_id  = each.value.id`
![image](https://user-images.githubusercontent.com/23193161/231131242-333c6d45-1ac0-497e-81f9-1bcd2a67ec0f.png)

**Comment by TomasKunka** [comment]
I was digging a little deeper. I think it might be caused just by a typo. in [users.go](https://github.com/databricks/terraform-provider-databricks/blob/e30e31beb3fd483ba4be4ec8019b0bffca3b8590/scim/resource_user.go#L101) (Read/Update) source `externalID` is used instead of `externalId`.  

I tested querying API with `attributes=externalID` and it returned no external id in the response. with `attributes=externalId`, correct external id is returned

**Comment by nkvuong** [comment]
@TomasKunka you are right...

actually the bug is likely from the below 2 lines - let me raise a quick PR and test them

https://github.com/databricks/terraform-provider-databricks/blob/e30e31beb3fd483ba4be4ec8019b0bffca3b8590/scim/resource_user.go#L84

https://github.com/databricks/terraform-provider-databricks/blob/e30e31beb3fd483ba4be4ec8019b0bffca3b8590/scim/resource_user.go#L149
