### ISSUE TITLE
[FEATURE] Issue with `databricks_sql_dashboard` resource

### ISSUE THREAD

**Issue by fjakobs** [databricks/terraform-provider-databricks#2508]
In the Query Resource, you can define Run As Role to be Viewer for example: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_query but not in dashboards: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_dashboard 

Could we add `run_as_role` and `data_source_id` fields for dashboard resource?

**Comment by DerrickRZhang** [comment]
Can I ask here how you successfully created the query dashboard and query through tf? Is there any additional requirement on the data source to be used by query since I have an sql endpoint used by other jobs. But the data source id fetched from this sql endpoint raises an error when used by the query.

**Comment by mgyucht** [comment]
@DerrickRZhang If you have another question that is not relevant to this feature request, I recommend you open a new issue.

@fjakobs If you're interested in this, consider following up with the Redash or Lakeview teams.

**Comment by lakshmirajagopalan** [comment]
Was there any update on the above? Where can i find this field?

**Comment by alexott** [comment]
it's not merged yet...

**Comment by lakshmirajagopalan** [comment]
Thanks @alexott . Please let us know once available. We have started using this extensively.
