### ISSUE TITLE
[ISSUE] Issue with Experimental Terraform Provider - notebook exporter

### ISSUE THREAD

**Issue by zshao9** [databricks/terraform-provider-databricks#3081]
File names with "/" are not exported correctly.

```
> ./terraform-provider-databricks_v1.33.0_with_sql-is-owner-permission exporter -directory xxxx
[ERROR] Failed custom import of databricks_notebook[_users_uuuu_read_write_back_to_kafka] (id: /Users/uuuu@example.com/Read / write back to kafka): Path (/Users/uuuu@example.com.com/Read / write back to kafka) doesn't exist.

```

The notebook title has "/" in it.  Does that require escaping or something to read correctly?

**Comment by alexott** [comment]
It's a regression that existed in the new UI for some time - it allowed to creation of notebooks with `/` in the name. But this broke the underlying APIs that use the file path as a key.  The issue was fixed in UI a few months ago, but old notebooks still exist.  The only workaround is to rename the notebook.

**Comment by zshao9** [comment]
Thanks for the context @alexott .  I renamed the notebook.
