### ISSUE TITLE
[ISSUE] Issue with `databricks_mws_workspaces` resource - `storage_customer_managed_key_id`

### ISSUE THREAD

**Issue by seb-kainos-arqiva** [databricks/terraform-provider-databricks#3303]
### Configuration
```hcl
resource "databricks_mws_workspaces" "this" {
  [...]
  storage_customer_managed_key_id = databricks_mws_customer_managed_keys.data_encryption.id
  [...]
}
```

### Expected Behavior
Workspace created with no errors.

### Actual Behavior
```
Error: cannot create mws workspaces: MALFORMED_REQUEST: Invalid customerManagedKeyId: 77d55848-...../a9e47455-...
```

### Workaround
```hcl
resource "databricks_mws_workspaces" "this" {
  [...]
  storage_customer_managed_key_id = split("/", databricks_mws_customer_managed_keys.data_encryption.id)[1]
  [...]
}
```

### Terraform and provider versions
Databricks: `1.37.1`
Terraform: latest

### Is it a regression?
Don't know.

**Comment by tanmay-db** [comment]
Hi @seb-kainos-arqiva, thanks for reaching out. This is an expected behaviour. Please take a look at the docs: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_customer_managed_keys.

Highlighting the relevant section:
`````
# supply databricks_mws_customer_managed_keys.managed_services.customer_managed_key_id as managed_services_customer_managed_key_id for databricks_mws_workspaces
`````

Closing the issue for time being, please reopen if that doesn't work.
