### ISSUE TITLE
[DOC] wrong assume_role_policy argument in example

### ISSUE THREAD

**Issue by rareal** [databricks/terraform-provider-databricks#3655]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_unity_catalog_policy#example-usage

### Expected Details
in 
```terraform
resource "aws_iam_role" "metastore_data_access" {
  name                = "${var.prefix}-uc-access"
  assume_role_policy  = data.aws_iam_policy_document.passrole_for_uc.json
  managed_policy_arns = [aws_iam_policy.unity_metastore.arn]
}
``` 
the assume_role_policy is taking `data.aws_iam_policy_document.passrole_for_uc.json`, but the example defined `data "databricks_aws_unity_catalog_assume_role_policy" "this"`

### Fix
```terraform
resource "aws_iam_role" "metastore_data_access" {
  name                = "${var.prefix}-uc-access"
  assume_role_policy  = data.databricks_aws_unity_catalog_assume_role_policy.this.json
  managed_policy_arns = [aws_iam_policy.unity_metastore.arn]
}
```

**Comment by sbchapin** [comment]
FWIW, this issue is still affecting users.  I assume it just hasn't been published, as the `latest` tag in the docs is still erroneous (as of Aug 26th).

As long as the documentation is not republished, it will be affecting at least these three pages:
- https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_unity_catalog_assume_role_policy
- https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_unity_catalog_policy
- https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog
