### ISSUE TITLE
[ISSUE] Checksum changed for 1.47.0?

### ISSUE THREAD

**Issue by janosdebugs** [databricks/terraform-provider-databricks#3660]
Hey folks, OpenTofu maintainer here. We received a complaint from a user that the checksum for Linux/AMD64 version 1.47.0 changed from `c89f9dcd0b6159d3f15e74083c0e71dc7d799ed8ae61385b5962c8394314b684` to `a4b2ebf71205365d3d30be4f288c100359a81c40da9f37e23947c9dea3521b3c` and they are unable to install the provider.

Can someone with a visible org membership in the Databricks GitHub organization please **confirm that this is not a supply chain attack** and we are safe to reindex the provider? (We treat versions as soft-immutable to protect against supply chain attacks.)

(Also, if I may ask for an additional favor, could you please submit your [public GPG key here](https://github.com/opentofu/registry/issues/new/choose) so we can verify the binaries in the future?)

**Comment by pietern** [comment]
Hi! It is possible they observed a different hash for a very brief time window (max 15 mins). We had to run the release twice because the goreleaser action was broken ([action log](https://github.com/databricks/terraform-provider-databricks/actions/workflows/release.yml)). The hashes you mention are both listed in the two separate job runs of goreleaser, so they are both expected.

We can submit our GPG key.

Thanks for raising this!

**Comment by oliverangelil** [comment]
Issue continues to pop up right now.
Experiencing the same in two separate and independent VMs.

![image](https://github.com/databricks/terraform-provider-databricks/assets/15682787/8d03ef25-39c4-4b74-8e96-6176508e0eb3)

**Comment by oliverangelil** [comment]
fixed now. Thanks for the impressive turnaround time both!
